tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "openresty/brew"

brew "asdf"
brew "bash-completion"
brew "bash"
brew "cmake"
brew "coreutils"
brew "docker-compose", link: false
brew "exiftool"
brew "ffmpeg"
brew "gcc"
brew "git"
brew "go"
brew "gphoto2"
brew "gsl"
brew "heroku/brew/heroku"
brew "imagemagick"
brew "jq"
brew "jupyterlab", link: false
brew "lua@5.1"
brew "luarocks"
brew "node"
brew "openresty/brew/openresty"
brew "openssl"
brew "overmind"
brew "pandoc"
brew "pcre"
brew "postgresql@14"
brew "python3"
brew "qt"
brew "redis"
brew "ruby"
brew "sqlite"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zlib"

cask "1password-cli"
cask "1password"
cask "audio-hijack"
# cask "canon-captureontouch-utility"
cask "canon-eos-utility"
cask "canon-eos-webcam-utility"
cask "carbon-copy-cloner"
cask "chromedriver"
cask "discord"
# cask "displaycal"
cask "docker"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "font-inconsolata"
cask "font-source-code-pro"
cask "geekbench"
cask "google-chrome-canary"
cask "google-chrome"
cask "launchbar"
cask "mactex-no-gui"
# cask "ngrok"
cask "obs"
cask "slack"
cask "visual-studio-code-insiders"
# cask "visual-studio-code"
cask "zoom"
cask "zulip"
