#! /usr/bin/env bash
# macOS: This file is sourced by bash_profile, close to the top.

# Shorthand just for readability.
BREW=$HOMEBREW_PREFIX;
# TODO: Do I need INTEL_BREW or ARM_BREW prefixes...

# Luarocks 3 and Lua 5.1 tools (added by snapCloud)
# This assumes everything is lua 5.1, fine for me...
LUAROCKS_VERSION=$(ls $HOMEBREW_CELLAR/luarocks | tail -n 1);
export LUA_VERSION="5.1"
lua_paths=(
  "./?.lua"
  "./?/init.lua"
  "$BREW/lib/lua/5.1/?.lua"
  "$BREW/lib/lua/5.1/?/init.lua"
  "$BREW/share/lua/5.1/?.lua"
  "$BREW/share/lua/5.1/?/init.lua"
  "$HOME/.luarocks/share/lua/5.1/?.lua"
  "$HOME/.luarocks/share/lua/5.1/?/init.lua"
  "$HOMEBREW_CELLAR/luarocks/$LUAROCKS_VERSION/share/lua/5.1/?.lua"
)
for str in ${lua_paths[@]}; do
  export LUA_PATH="$str;$LUA_PATH";
done

lua_cpaths=(
"./?.so"
"$BREW/lib/lua/5.1/?.so"
"$BREW/lib/lua/5.1/loadall.so"
"$HOME/.luarocks/lib/lua/5.1/?.so"
)
for str in ${lua_cpaths[@]}; do
  export LUA_CPATH="$str;$LUA_CPATH";
done


# This is odd... https://stackoverflow.com/a/53404317
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Luarocks 3 and Lua 5.1 tools (added by snapCloud).
export LUA_PATH='/opt/homebrew/Cellar/luarocks/3.9.2/share/lua/5.1/?.lua;/usr/local/Cellar/luarocks/3.9.2/share/lua/5.1/?.lua;/Volumes/Michael/Users/michael/.luarocks/share/lua/5.1/?/init.lua;/Volumes/Michael/Users/michael/.luarocks/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;./?/init.lua;./?.lua;;/Users/michael/.luarocks/share/lua/5.1/?.lua;/Users/michael/.luarocks/share/lua/5.1/?/init.lua;/opt/homebrew/share/lua/5.1/?.lua;/opt/homebrew/share/lua/5.1/?/init.lua'
export LUA_CPATH='/Volumes/Michael/Users/michael/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;/usr/local/lib/lua/5.1/?.so;./?.so;;/Users/michael/.luarocks/lib/lua/5.1/?.so;/opt/homebrew/lib/lua/5.1/?.so'
