# Sigh...macOS....
export BASH_SILENCE_DEPRECATION_WARNING=1


# Setup homebrew first.
# /usr/local/bin deprecated on ARM but included b/c some tools still use it.
# brew needs to be in the PATH first.
BREW_INTEL='/usr/local'
BREW_ARM='/opt/homebrew'
export PATH="$BREW_ARM/bin:$BREW_INTEL/bin:$PATH"

# Complexity here handles both ARM + Intal macOS versions
# Bash Completion for brew programs + brew setup
if type brew &> /dev/null; then
  export HOMEBREW_PREFIX="$(brew --prefix)";
  export HOMEBREW_CELLAR="${HOMEBREW_PREFIX}/Cellar";
  export HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}";
  export PATH="${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:$PATH";
  export MANPATH="${HOMEBREW_PREFIX}/share/man${MANPATH+:$MANPATH}:";
  export INFOPATH="${HOMEBREW_PREFIX}/share/info:${INFOPATH:-}";
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
else
  echo "BREW NOT FOUND"
fi


# Setup ALL PATH customizations here, HOMEBREW is setup.
[ -n "$PS1" ] && source ~/.bashrc

# Load the shell dotfiles, and then some:
for file in $HOME/Dropbox/Projects/dotfiles/source/*; do
    [ -r "$file" ] && source "$file"
done
unset file

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null
done

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion

# TODO: Add the flag for zsh and uncomment.
# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
#   autoload -Uz compinit
#   compinit
# fi

eval "$(gh completion -s bash)"
source <(luarocks completion bash)

# Needed from some homebrew functions.
# Most especially needed for pdflatex and mactex-no-gui
eval "$(/usr/libexec/path_helper)"

if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

source $(brew --prefix)/opt/asdf/libexec/asdf.sh
source $(brew --prefix)/opt/asdf/etc/bash_completion.d/asdf.bash

export PATH="$(brew --prefix)/sbin:$PATH"

# Brew bin paths already loaded so brew can be loaded.
paths=(
  "./bin"
  "/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin"
  "/Applications/Visual\ Studio\ Code\ Insiders.app/Contents/Resources/app/bin"
  "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
  "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
  "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
  "$HOME/.luarocks/bin"
  "$HOME/bin"
  "$HOME/Library/Python/3.9/bin"
  "$HOME/Library/TexShop/bin"
  "/Library/Tex/texbin"
  "/Library/Apple/usr/bin"
  "/opt/X11/bin"
  "/System/Cryptexes/App/usr/bin"
  "/usr/bin"
  "/usr/sbin"
  "/sbin"
  "/bin"
)
for str in ${paths[@]}; do
  PATH="$PATH:$str";
done
export PATH=$PATH
export PATH="/opt/homebrew/opt/postgresql@16/bin:$PATH"
