[tools]
node = ["lts", "18", "20"]
ruby = ["3.3.8", "3.4"]
python = "3.13"

[env]
# Python with tkinter support
PYTHON_CONFIGURE_OPTS = "--with-tkinter"
# Intel Mac brew paths
LDFLAGS = "-L/usr/local/lib"
CPPFLAGS = "-I/usr/local/include"
PKG_CONFIG_PATH = "/usr/local/lib/pkgconfig"
